# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField(default=None)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('lst_ord_date', models.DateTimeField(blank=True, null=True)),
                ('nxt_ord_date', models.DateField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, max_length=200)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('mage_cust_id', models.IntegerField(blank=True, null=True)),
                ('first', models.CharField(blank=True, max_length=200)),
                ('last', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('prod_id', models.IntegerField(blank=True, null=True)),
                ('prod_name', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12)),
                ('qty', models.IntegerField(default=0)),
                ('ship_method', models.CharField(blank=True, max_length=200)),
                ('mage_bill_addy', models.IntegerField(blank=True, null=True)),
                ('mage_ship_addy', models.IntegerField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=200)),
                ('coupon', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NODSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('left', models.DateField()),
                ('ng_red3_l', models.IntegerField()),
                ('ng_white3_l', models.IntegerField()),
                ('ng_variety3_l', models.IntegerField()),
                ('ng_red6_l', models.IntegerField()),
                ('ng_white6_l', models.IntegerField()),
                ('ng_variety6_l', models.IntegerField()),
                ('g_red3_l', models.IntegerField()),
                ('g_white3_l', models.IntegerField()),
                ('g_variety3_l', models.IntegerField()),
                ('right', models.DateField()),
                ('end', models.DateField()),
                ('ng_red3_r', models.IntegerField()),
                ('ng_white3_r', models.IntegerField()),
                ('ng_variety3_r', models.IntegerField()),
                ('ng_red6_r', models.IntegerField()),
                ('ng_white6_r', models.IntegerField()),
                ('ng_variety6_r', models.IntegerField()),
                ('g_red3_r', models.IntegerField()),
                ('g_white3_r', models.IntegerField()),
                ('g_variety3_r', models.IntegerField()),
                ('red3_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('white3_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('red6_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('white6_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('variety3_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('variety6_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('fm_churn', models.DecimalField(decimal_places=4, max_digits=12)),
                ('nfm_churn', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pop_ng', models.IntegerField()),
                ('pop_gi', models.IntegerField()),
                ('pop_tot', models.IntegerField()),
                ('pop_3pack', models.IntegerField()),
                ('pop_6pack', models.IntegerField()),
                ('wa', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='weighted_average')),
                ('bot_red', models.IntegerField()),
                ('bot_white', models.IntegerField()),
                ('red_perc', models.DecimalField(decimal_places=4, max_digits=12)),
                ('white_perc', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tot_pack', models.IntegerField()),
                ('tot_bottles', models.IntegerField()),
                ('red_bottles', models.IntegerField()),
                ('white_bottles', models.IntegerField()),
                ('tot_cases', models.IntegerField()),
                ('red_cases', models.IntegerField()),
                ('white_cases', models.IntegerField()),
                ('reds_each', models.IntegerField()),
                ('whites_each', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('new_member', models.IntegerField(default=10)),
                ('new_gift_member', models.IntegerField(default=0)),
                ('buffer', models.IntegerField(default=100)),
                ('r2w1_percent', models.DecimalField(decimal_places=4, default=0.6, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Update'),
        ),
        migrations.AddField(
            model_name='nodsplit',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Update'),
        ),
    ]
